name:                servant-hasql
version:             0.1.0.0
github:              "lupusanay/servant-hasql"
license:             MIT
author:              "Ilya Kopeshtianski"
maintainer:          "lupusanay@gmail.com"
copyright:           "2019 Ilya Kopeshtianski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lupusanay/servant-hasql#readme>

dependencies:
- base >= 4.7 && < 5
- swagger2
- aeson-pretty
- servant-server
- servant-swagger
- servant
- hasql
- hasql-th
- hasql-pool
- aeson
- text
- vector
- bytestring
- mtl
- wai
- warp
- profunctors

default-extensions:
- OverloadedStrings
- QuasiQuotes
- DataKinds
- DeriveGeneric
- GeneralizedNewtypeDeriving
- DeriveFunctor
- TemplateHaskell
- TypeOperators
- FlexibleContexts

library:
  source-dirs: src

executables:
  servant-hasql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-hasql

tests:
  servant-hasql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-hasql
